### PR TITLE
ENH: Added two demos

### PR DESCRIPTION
**Pull request by rstoneback**
Two demos are included:

Demo 1:
 - Download, load, and plot data from ACE

Demo 2:
 - Download, load, modify, and plot a different instrument from ACE
 

Incidentally I haven't found a good way to share things like this via twitter. I can post plots directly. That's good. For the code I can post a screenshot... I can also provide a link to a jupyter notebook viewer but it doesn't render in twitter so shows up as a link. I don't think people tend to click on links. A whole extra level of interaction that just having the tweet scroll by with visual info already there.

### CODE REVIEW

**Comment by rstoneback** [comment]
Technically still not 'back on' pysat yet but if I don't push the button chances are I may forget.

**Comment by aburrell** [comment]
So... how do I tests these?  I am not familiar with notebooks so I need lots of instructions for how to use the files you have here.

**Comment by rstoneback** [comment]
> So... how do I tests these? I am not familiar with notebooks so I need lots of instructions for how to use the files you have here.

No problem. First you need `jupyter` from PyPi. After downloaded and installed you'll need to start the jupyter server via the terminal, `jupyter notebook`. That'll start a python process and a web server and will load up your default browser to the jupyter interface. It'll open in the same directory you run the command. To make things easy I suggest putting the demo `.ipynb` in the same directory. Open one of the `.ipynb` files via the web browser and it should look like, https://github.com/pysat/pysatTutorials/blob/3e3819624653da1fd95e364ca61cc13d616b0bb3/pysatTutorials/custom_attach_demo.ipynb 

Each code block needs to be run in order. Click a group of lines and hit shift + enter to run. Run all the code blocks in order and the plots that are there originally should be reproduced. You can also hit a button at the top that looks like a fast forward symbol. It'll run all the code in order for you. You'll have to reset your pysat settings to point to your original data directory at the end.

I'm prepping for a PyHC meeting this morning but will be back this afternoon.

**Comment by rstoneback** [comment]
Should I move copies of these examples into pysatSpaceWeather? pysat? For twitter I need something to link to, and pysatTutorials is off over here by itself which can make that easier. I'd prefer a longer term life for the example though.

**Comment by aburrell** [comment]
How about adding links to these ACE tutorials in pysatSW?

**Comment by rstoneback** [comment]
I'll take a look.

**Comment by rstoneback** [comment]
To pragmatically link the links need to remain valid as long as possible. I'm thinking for pysatTutorials that we merge into main instead of develop. A continuous release project.

**Comment by JonathonMSmith** [comment]
I'm so confused by netlify lol
What is gifted-thompson? It looks like the preview app/site that netlify generated is broken... or something.

**Comment by JonathonMSmith** [comment]
So right now, if you open this branch in binder, you need to install some dependencies.
If we include a "requirements.txt" with matplotlib, pysatMadrigal, and pysatSpaceWeather most of the tutorials will run out of the box. 
The DMSP tutorial is currently broken because you need to add dmsp to the instrument register.
We can make that change here, but maybe it's best left as an issue to be fixed in another pull (I'm happy to do this)

**Comment by rstoneback** [comment]
> I'm so confused by netlify lol
> What is gifted-thompson? It looks like the preview app/site that netlify generated is broken... or something.

I think I need to ping the source on this one. Once we get our pysat issues out of the way I'll ping some PyHC folks.

**Comment by rstoneback** [comment]
> So right now, if you open this branch in binder, you need to install some dependencies.
> If we include a "requirements.txt" with matplotlib, pysatMadrigal, and pysatSpaceWeather most of the tutorials will run out of the box.
> The DMSP tutorial is currently broken because you need to add dmsp to the instrument register.
> We can make that change here, but maybe it's best left as an issue to be fixed in another pull (I'm happy to do this)

Thanks! Its alive! All three demos here ran on binder.

**Comment by rstoneback** [comment]
Ready for re-review.

**Comment by JonathonMSmith** [comment]
Interestingly when I try to run the DMSP demo on binder I still get an error. 
**pysat.params['data_dirs'] needs to be set before registering the models.** 
I just set it to './' since I don't know the best place to put it for notebooks. 
--side note--
I don't think binder ever looks at your local development environment like normal notebooks do, so I'm not sure why these issues are only showing up in my binder sessions.
my process:
go to mybinder.org
type in the repo name: https://github.com/pysat/pysatTutorials/
choose the demo_ace branch
click "Launch"

**Comment by rstoneback** [comment]
Thanks for the note. I corrected the notebook. The DMSP example was the last one I ran. My pysat directory was set on the binder session by both of the previous examples, so I didn't get the error.

**Comment by rstoneback** [comment]
oops, and my process is to click the link I posted above :)
I think you ran into the DMSP example bug by order of ops, good thing you did though.

**Review by JonathonMSmith — APPROVED** [review]
Oh I see now, the other notebooks had the params setting. Well everything is running as expeected on startup now!

**Comment by rstoneback** [comment]
> Oh I see now, the other notebooks had the params setting. Well everything is running as expeected on startup now!

Thanks! In case you don't check slack very often I have a question posted for ya 🙈

**Comment by rstoneback** [comment]
Apologies for the *just one more thing*, but the ICON demo was in the branch because of an old pull and would be released to main here. It was out of date so I updated it. Another review requested 😃

**Comment by JonathonMSmith** [comment]
Alright one issue and then some notes. First the issue:
The first chunk of imports fails because pysatNASA needs 'data_dirs' to be set beforehand. It's easy enough to just execute the second chunk and then the first one again, but it might be nice to move the pysatNASA import after the 'data_dirs' specification.

As for notes, I think it's a nonissue, but there are a lot of warnings. The only reason I even bring this up is that binder likes to highlight these things in red... which might be intimidating for new users of python/jupyter/binder/pysat. Not sure really what to do about this as the logger INFO is pretty helpful I think, but binder highlighting it red gives the impression that something is wrong.

**Comment by rstoneback** [comment]
Thanks for the comments. I added some notes about the couple warnings I did see. I also added comments and the logging feedback that is shown by default in a couple areas. It is all red but not a warning. Hopefully users catch the comment in each respective cell.

I updated the import statement order so users don't have to backtrack or try and sort things out.

I also added basic info to the readme. With a link to binder and the main branch.

**Comment by JonathonMSmith** [comment]
okay this looks great!

**Pull request merged**
